{% set name = "gspread-pandas" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gspread-pandas-{{ version }}.tar.gz
  sha256: aac84bd63594db6271ad2cfe10be64614ea5d1129d063ca57b40c2b9dcc18013

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pytest-runner
    - pip
  run:
    - python >={{ python_min }}
    - gspread >=5.0.0,<6
    - pandas >=0.20.0
    - decorator
    - google-auth
    - google-auth-oauthlib

test:
  imports:
    - gspread_pandas
  commands:
    - pip check
  requires:
    - pip
    - pytest

about:
  home: https://github.com/aiguofer/gspread-pandas
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A package to easily open an instance of a Google spreadsheet and interact with worksheets through Pandas DataFrames.
  doc_url: https://gspread-pandas.readthedocs.io/en/latest
  dev_url: https://github.com/aiguofer/gspread-pandas

extra:
  recipe-maintainers:
    - mariusvniekerk
